### ISSUE TITLE
exception raised on OS environment setting 'AWS_DEFAULT_REGION'

### ISSUE THREAD

**Issue by SpectrumScaleOnAWS** [aws-quickstart/taskcat#136]
**Describe the bug**
unable to run taskcat using latest version 2018.913.194818
getting below errors.
Traceback (most recent call last):
  File "/usr/local/bin/taskcat", line 72, in <module>
    main()
  File "/usr/local/bin/taskcat", line 60, in main
    tcat_instance.stage_in_s3(taskcat_cfg)
  File "/usr/local/lib/python3.6/site-packages/taskcat/stacker.py", line 415, in stage_in_s3
    s3_client = self._boto_client.get('s3', region=self.get_default_region(), s3v4=True)
  File "/usr/local/lib/python3.6/site-packages/taskcat/utils.py", line 118, in get
    region = os.environ['AWS_DEFAULT_REGION']
  File "/usr/lib64/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'AWS_DEFAULT_REGION'

**Comment by avattathil** [comment]
Please add steps to recreate

**Comment by jaymccon** [comment]
Looks like [TaskCat.aws_api_init](https://github.com/aws-quickstart/taskcat/blob/master/taskcat/stacker.py#L1782-L1788) is only setting a default region if `--boto_profile` , `--aws_access_key` and/or `--aws_secret_key` are not passed.
