### ISSUE TITLE
docker version of taskcat 0.7.5 failing with cfnlint' has no attribute 'decode'

### ISSUE THREAD

**Issue by vsnyc** [aws-quickstart/taskcat#148]
**Describe the bug**
Latest docker version 0.7.5 of taskcat is failing with the following error:

[taskcat] :Validate Template in test[quickstart-tableau-server]
[DEBUG  ] :cleanup set by cli flag False
Traceback (most recent call last):
  File "/usr/local/bin/taskcat", line 79, in <module>
    main()
  File "/usr/local/bin/taskcat", line 66, in main
    tcat_instance.validate_template(taskcat_cfg, test_list)
  File "/usr/local/lib/python3.6/site-packages/taskcat/stacker.py", line 648, in validate_template
    self.define_tests(taskcat_cfg, test)
  File "/usr/local/lib/python3.6/site-packages/taskcat/stacker.py", line 1560, in define_tests
    m_constructor = cfnlint.decode.cfn_yaml.multi_constructor
AttributeError: module 'cfnlint' has no attribute 'decode'

**To Reproduce**
1. Pull latest docker image
2. Run any taskcat test

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/taskcat/commit/8787dec5d21647fa0a84bb1a7be80243234eba77

**Comment by vsnyc** [comment]
Verified
