### ISSUE TITLE
Deep Cleanup Fails

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/taskcat#194]
```
22:49:35 [INFO   ] :Few stacks failed to delete. Collecting resources for deep clean-up.
22:49:35 Traceback (most recent call last):
22:49:35   File "/var/lib/jenkins/.local/bin/taskcat", line 104, in <module>
22:49:35     main()
22:49:35   File "/var/lib/jenkins/.local/bin/taskcat", line 97, in main
22:49:35     tcat_instance.cleanup(testdata, 5)
22:49:35   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/taskcat/stacker.py", line 1322, in cleanup
22:49:35     self.deep_cleanup(testdata_list)
22:49:35   File "/var/lib/jenkins/.local/lib/python3.6/site-packages/taskcat/stacker.py", line 1350, in deep_cleanup
22:49:35     failed_stacks = CfnResourceTools.get_all_resources(failed_stack_ids, region)
22:49:35 TypeError: get_all_resources() missing 1 required positional argument: 'region'
22:49:35 Build step 'Execute shell' marked build as failure
22:49:35 Checking console output
22:49:35 Build did not succeed and the project is configured to only push after a successful build, so no pushing will occur.
22:49:35 Finished: FAILURE
```

**Comment by avattathil** [comment]
Fixed in version [0.8.12]( https://github.com/aws-quickstart/taskcat/releases/tag/0.8.12)  commit https://github.com/aws-quickstart/taskcat/commit/922232449890083f60f2d11d9e57bb2c2dc8b2cb
