### ISSUE TITLE
AttributeError: module 'botocore.vendored.requests' has no attribute 'get'

### ISSUE THREAD

**Issue by pandithdurai** [aws-quickstart/taskcat#342]
**Describe the bug**
vendored version of requests removed from Botocore. Please find below the post from AWS

https://aws.amazon.com/blogs/developer/removing-the-vendored-version-of-requests-from-botocore/

But it's not handled in task cat version taskcat-0.8.47 which is latest

Please find below the error while generating taskcat report.

Traceback (most recent call last): 
  File "/usr/local/bin/taskcat", line 101, in <module> 
    main() 
  File "/usr/local/bin/taskcat", line 90, in main 
    tcat_instance.createreport(testdata, 'index.html') 
  File "/usr/local/lib/python3.6/site-packages/taskcat/stacker.py", line 1495, in createreport 
    cfn_report.generate_report() 
  File "/usr/local/lib/python3.6/site-packages/taskcat/generate_reports.py", line 70, in generate_report 
    output_css = requests.get(css_url).text 
AttributeError: module 'botocore.vendored.requests' has no attribute 'get'

**Version 
 - Taskcat version - taskcat-0.8.47

**Comment by tobilebonk** [comment]
same problem here :(

**Comment by avattathil** [comment]
fixed in https://github.com/aws-quickstart/taskcat/pull/343
