### ISSUE TITLE
Parameterless configuration yields AttributeError 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by villasv** [aws-quickstart/taskcat#355]
Having no parameters set in the `tascat.yaml` file will error:

```
Traceback (most recent call last):
  File "/home/villasv/.local/lib/python3.6/site-packages/taskcat/_cli.py", line 66, in main
    cli.run()
  File "/home/villasv/.local/lib/python3.6/site-packages/taskcat/_cli_core.py", line 228, in run
    return getattr(command(), subcommand)(**args)
  File "/home/villasv/.local/lib/python3.6/site-packages/taskcat/_cli_modules/test.py", line 73, in run
    parameters = config.get_rendered_parameters(buckets, regions, templates)
  File "/home/villasv/.local/lib/python3.6/site-packages/taskcat/_config.py", line 305, in get_rendered_parameters
    for param_key, param_value in test.parameters.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

**To Reproduce**
`taskcat test run` with an input file without parameters.

**Expected behavior**
Use the default parameters in the target stack.

**Version**
 - Taskcat Version: 0.9.0
- Python Version 3.6.5

**Comment by andrew-glenn** [comment]
@villasv  Thanks. I figured you would be testing it out soon enough . :) 

By the way, amiupdater didn't make the cut for the 0.9.0 release. I'm working on adding it in now. We have a pretty big dependency on it as well, so we're hurting as much as you are. just an FYI

**Comment by villasv** [comment]
No problem! I'm just testing out the migration effor for taskcat 0.9 :-)
