### ISSUE TITLE
Exception while processing child stack

### ISSUE THREAD

**Issue by asaushkin** [aws-quickstart/taskcat#366]
**Describe the bug**

I got an error while run command ` taskcat -d test run`

```
[ERROR  ] : TypeError write() argument must be str, not collections.OrderedDict
Traceback (most recent call last):
  File "/home/ags/venv/venv-taskcat/lib/python3.6/site-packages/taskcat/_cli.py", line 66, in main
    cli.run()
  File "/home/ags/venv/venv-taskcat/lib/python3.6/site-packages/taskcat/_cli_core.py", line 228, in run
    return getattr(command(), subcommand)(**args)
  File "/home/ags/venv/venv-taskcat/lib/python3.6/site-packages/taskcat/_cli_modules/test.py", line 81, in run
    terminal_printer.report_test_progress(stacker=test_definition)
  File "/home/ags/venv/venv-taskcat/lib/python3.6/site-packages/taskcat/_tui.py", line 24, in report_test_progress
    self._print_stack_tree(stack, buffer=self.buffer)
  File "/home/ags/venv/venv-taskcat/lib/python3.6/site-packages/taskcat/_tui.py", line 37, in _print_stack_tree
    if stack.descendants():
  File "/home/ags/venv/venv-taskcat/lib/python3.6/site-packages/taskcat/_cfn/stack.py", line 495, in descendants
    self._fetch_children()
  File "/home/ags/venv/venv-taskcat/lib/python3.6/site-packages/taskcat/_cfn/stack.py", line 481, in _fetch_children
    stack_obj = Stack._import_child(stack, self)
  File "/home/ags/venv/venv-taskcat/lib/python3.6/site-packages/taskcat/_cfn/stack.py", line 335, in _import_child
    fh.write(tempate_body)
TypeError: write() argument must be str, not collections.OrderedDict
```

**Version (Please make sure you are running the latest version of taskcat)
 
```
Name: taskcat
Version: 0.9.0
Summary: An OpenSource Cloudformation Deployment Framework
Home-page: https://aws-quickstart.github.io/taskcat/
Author: Tony Vattathil, Jay McConnell, Andrew Glenn, Santiago Cardenas, Shivansh Singh
Author-email: tonynv@amazon.com, jmmccon@amazon.com, andglenn@amazon.com, sshvans@amazon.com
License: Apache License 2.0
Location: /home/ags/venv/venv-taskcat/lib/python3.6/site-packages
Requires: boto3, pyfiglet, yattag, PyYAML, tabulate, jinja2, jsonschema, mock, dataclasses-jsonschema, requests, reprint, dataclasses, setuptools, cfn-lint, docker, dulwich, botocore
Required-by: 
```

**Additional context**

I use custom cloudformation template with child stacks.

It looks like that error here (_cfn/stack.py) - write expect str not an OrderedDict:

```python
...
            if not absolute_path.exists():
                with open(absolute_path, "w") as fh:
                    fh.write(tempate_body)
...
```

**Comment by asaushkin** [comment]
Are there any examples how to run taskcat on custom cloudformation template with child stacks?

**Comment by jaymccon** [comment]
@asaushkin the child stack processing was improved in 0.9.1, but you might still encounter (non-fatal) errors due to a typo, a fix for which will be in the next release, or you can install from `master` in the meantime.

**Comment by asaushkin** [comment]
@jaymccon Thanks!
