### ISSUE TITLE
Parameters replace fail when empty dict is passwd 

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/taskcat#391]
**Sample config file**

```
project:
  name: cfn-project
tests:
  mytest:
    template: templates/lab1.template.yaml
    regions:
    - us-east-1
     parameters: {}
```

```
[ERROR  ] : TypeError expected string or bytes-like object
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/taskcat/_cli.py", line 70, in main
    cli.run()
  File "/usr/local/lib/python3.7/site-packages/taskcat/_cli_core.py", line 228, in run
    return getattr(command(), subcommand)(**args)
  File "/usr/local/lib/python3.7/site-packages/taskcat/_cli_modules/test.py", line 75, in run
    parameters = config.get_rendered_parameters(buckets, regions, templates)
  File "/usr/local/lib/python3.7/site-packages/taskcat/_config.py", line 295, in get_rendered_parameters
    region_params, s3bucket.name, region.name, region.client
  File "/usr/local/lib/python3.7/site-packages/taskcat/_template_params.py", line 49, in __init__
    self.transform_parameter()
  File "/usr/local/lib/python3.7/site-packages/taskcat/_template_params.py", line 64, in transform_parameter
    self._regex_replace_param_value(self.RE_GENNUMB, self._gen_rand_num(20))
  File "/usr/local/lib/python3.7/site-packages/taskcat/_template_params.py", line 336, in _regex_replace_param_value
    if self.regxfind(regex_pattern, self.param_value):
  File "/usr/local/lib/python3.7/site-packages/taskcat/_common_utils.py", line 76, in regxfind
    security_group = re_object.search(data_line)
TypeError: expected string or bytes-like object
```

**To Reproduce**
Create a project with lambda source that does not require any inputs

Sample template:

```
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  S3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Description: >-
      S3 bucket name for the Quick Start assets. Quick Start bucket name can
      include numbers, lowercase letters, uppercase letters, and hyphens (-). It
      cannot start or end with a hyphen (-).
    Type: String
  S3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Can include numbers, lowercase letters, uppercase letters, hyphens (-), and forward slash (/).
    Default: 'cfn-project'
    Description: >-
      S3 key prefix where assets are located should end withforward slash (/).
    Type: String
Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:*
            Resource: arn:aws:logs:*:*:*
  GenRandomLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda creates simple random string
      Handler: lambda_function.handler
      Runtime: python3.7
      Role: !GetAtt 'LambdaExecutionRole.Arn'
      Timeout: 300
      Code:
        S3Bucket: !Ref 'S3BucketName'
        S3Key: !Sub '${S3KeyPrefix}lambda_functions/zips/GenRandom/lambda.zip'
```

**Comment by andrew-glenn** [comment]
https://github.com/aws-quickstart/taskcat/blob/b3e46e697236289954106b5def3a038a930f18e3/taskcat/_config.py#L282-L297


The value of line 284 is this
```
>>> param_dict
{'S3BucketName': None, 'S3KeyPrefix': 'cfn-project'}
>>>
```

This occurs because we're no longer validating using the <CloudFormation>.validate API. We need to catch these errors before we get to this point, as it's a regression.
