### ISSUE TITLE
Taskcat exits in get_teststate() when describestack fails

### ISSUE THREAD

**Issue by sshvans** [aws-quickstart/taskcat#64]
[taskcat] |GENERATING REPORTS
[INFO   ] :Creating report in [taskcat_outputs]
[INFO   ] :Collecting CloudFormation Logs
[INFO   ] :Collecting logs for tCaT-tag-quickstart-a-master-7e225ad7"

[ERROR  ] : Error trying to get the events for stack [tCaT-tag-quickstart-a-master-7e225ad7] in region [us-west-2 An error occurred (ValidationError) when calling the DescribeStackEvents operation: Stack [tCaT-tag-quickstart-a-master-7e225ad7] does not exist
[ERROR  ] :No event logs found. Something went wrong at describe event call.

[INFO   ] :(Generating Reports)
[INFO   ] : - Processing quickstart-a-master
Traceback (most recent call last):
  File "/usr/local/bin/taskcat", line 56, in <module>
    main()
  File "/usr/local/bin/taskcat", line 50, in main
    tcat_instance.createreport(testdata, 'index.html')
  File "/usr/local/lib/python3.6/site-packages/taskcat/stacker.py", line 1971, in createreport
    self.genreport(testdata_list, dashboard_filename)
  File "/usr/local/lib/python3.6/site-packages/taskcat/stacker.py", line 1750, in genreport
    state['region'])
  File "/usr/local/lib/python3.6/site-packages/taskcat/stacker.py", line 1658, in get_teststate
    test_query = cfn.describe_stacks(StackName=stackname)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 324, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 622, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id tCaT-tag-quickstart-a-master-7e225ad7 does not exist

**Comment by sshvans** [comment]
Fixed in commit c15582c12ea8a28a17a3193a06ed6325a7dcb4ab
