### ISSUE TITLE
SSM parameter types - for example, Type: "AWS::SSM::Parameter::Value<String>"

### ISSUE THREAD

**Issue by ozbillwang** [aws-quickstart/taskcat#680]
**Describe the bug**

When using the [SSM parameter types](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#aws-ssm-parameter-types) - for example, Type: "AWS::SSM::Parameter::Value<String>", taskcat can't fetch the ssm parameters.

```
ClientError An error occurred (ValidationError) when calling the CreateStack operation: Unable to fetch parameters [VPC] from parameter store for this account.

Exception ignored in: <function Pool.__del__ at 0x1217b2e50>
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.12/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 268, in __del__
    self._change_notifier.put(None)
  File "/usr/local/Cellar/python@3.8/3.8.12/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/usr/local/Cellar/python@3.8/3.8.12/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/usr/local/Cellar/python@3.8/3.8.12/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/local/Cellar/python@3.8/3.8.12/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
OSError: [Errno 9] Bad file descriptor
```

**To Reproduce**
When you use SSM parameter types in CFN

```
Parameters:
  VPC:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::VPC::Id>"
    Default: VPC
    Description: VPC ID
```

**Expected behavior**

**Screenshots**

**Version (Please make sure you are running the latest version of taskcat)

- taskcat version 0.9.23
- Python 3.8.12

**Comment by ozbillwang** [comment]
https://github.com/aws-quickstart/taskcat/pull/585 added some supports on parameter stores, but seems only support type `AWS::SSM::Parameter::Name`

![image](https://user-images.githubusercontent.com/8954908/132500246-d8386b6d-9515-492c-947c-98892a28e5ce.png)

**Comment by ozbillwang** [comment]
Close this ticket, because the problem is not in SSM.

taskcat doesn't work with Environment variables `AWS_PROFILE` and use my default profile, which the SSM parameter is not exist
