### ISSUE TITLE
Running taskcat with --public_s3_bucket as the only arg causes exception

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/taskcat#77]
jenkins@develop:workspace:[alfred] taskcat --public_s3_bucket
 _            _             _
| |_ __ _ ___| | _____ __ _| |_
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_
 \__\__,_|___/_|\_\___\__,_|\__|

version 2018.410.184245
Traceback (most recent call last):
  File "/var/lib/jenkins/.local/bin/taskcat", line 58, in <module>
    main()
  File "/var/lib/jenkins/.local/bin/taskcat", line 28, in main
    tcat_instance.set_config(args.config_yml)
  File "/var/lib/jenkins/.local/lib/python3.6/site-packages/taskcat/stacker.py", line 240, in set_config
    if os.path.isfile(config_yml):
  File "/usr/lib64/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/taskcat/commit/3abe74edb057e5882bf643d115c26c025b1ed284
