### ISSUE TITLE
utf decode fail when invoked with --public_s3_bucket

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/taskcat#78]
Traceback (most recent call last):
  File "/var/lib/jenkins/.local/bin/taskcat", line 58, in <module>
    main()
  File "/var/lib/jenkins/.local/bin/taskcat", line 46, in main
    tcat_instance.validate_template(taskcat_cfg, test_list)
  File "/var/lib/jenkins/.local/lib/python3.6/site-packages/taskcat/stacker.py", line 723, in validate_template
    self.define_tests(taskcat_cfg, test)
  File "/var/lib/jenkins/.local/lib/python3.6/site-packages/taskcat/stacker.py", line 1520, in define_tests
    if self.check_json(cfntemplate, quite=True, strict=False):
  File "/var/lib/jenkins/.local/lib/python3.6/site-packages/taskcat/stacker.py", line 1567, in check_json
    parms = json.loads(jsonin.decode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
Build step 'Execute shell' marked build as failure
Checking console output
Build did not succeed and the project is configured to only push after a successful build, so no pushing will occur.
Finished: FAILURE

**Comment by avattathil** [comment]
Fixed in https://github.com/aws-quickstart/taskcat/issues/66
