### ISSUE TITLE
Changes to pypi breaks version check 

### ISSUE THREAD

**Issue by avattathil** [aws-quickstart/taskcat#79]
Traceback (most recent call last):
  File "/usr/local/bin/taskcat", line 58, in <module>
    main()
  File "/usr/local/bin/taskcat", line 22, in main
    tcat_instance.welcome('taskcat')
  File "/usr/local/lib/python3.6/site-packages/taskcat/stacker.py", line 2192, in welcome
    self.checkforupdate()
  File "/usr/local/lib/python3.6/site-packages/taskcat/stacker.py", line 2173, in checkforupdate
    if version in current_version:
TypeError: argument of type 'NoneType' is not iterable

**Comment by avattathil** [comment]
Fix in https://github.com/aws-quickstart/taskcat/commit/eb9f9d9a57b6bd35e15cc5e0e6700b74470c7685

`[INFO   ] : A newer version of taskcat is available (2018.416.143234)`

**Please install the latest version** 
`[INFO   ] : To upgrade pip version    [ pip install --upgrade taskcat]`
`[INFO   ] : To upgrade docker version [ docker pull taskcat/taskcat ]`
